.TITLE		FLQ_MSG
.FACILITY	FLQ,1032/PREFIX=FLQ__
.IDENT		"V2.1"

.SEVERITY	ERROR
INVACC	    	<invalid access code>
RDONLY	    	<MX message queue open only for read access>
QUEFULL	    	<MX message queue full>
NOSUCHENT   	<entry number does not exist>
ENTMISMATCH 	<entry to be updated does not match currently locked entry>
NODPLNM		<No destination process logical name>
INVDSTPID	<Invalid destination process identifier>
NODSTPRC	<No destination process>
INVDENTNO	<invalid entry number>
QUEDISKFULL  	<MX message queue disk is too full to accept messages>

.SEVERITY       FATAL
OBSOLETE        <obsolete entry point referenced>

.END
