MX_FACILITY = MLFAKE
.INCLUDE [-]MMSDEFS.MMS

MLFAKE_OBJS = MLFAKE,MLFAKE_CLD

$(BINDIR)MLFAKE.EXE : $(BINDIR)MLFAKE.OLB($(MLFAKE_OBJS))
    $(LINK)/NOTRACE$(LINKFLAGS) $(BINDIR)MLFAKE.OLB/INCL=MLFAKE/LIB,$(STDOPTS)

PREFETCH :
